import { Roboto_Serif, Work_Sans } from "next/font/google";
import "./globals.css";
import Header from "./Component/Header/page";
import Footer from "./Component/Footer/page";
import Cards from "./Component/Cards/Cards";
import Form from "./Component/Form/page";
// import Terms from "./Component/Terms/Terms";
// import Privacy from "./Component/Privacy/Privacy";

const inter = Roboto_Serif({ subsets: ["latin"] });
const work = Work_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Footer />
        {/* <Form /> */}
        {/* <Privacy /> */}
      </body>{" "}
    </html>
  );
}
